In [71]:
import numpy as np
# from sklearn.linear_model import LinearRegression

In [72]:
x = np.array([[1, 2, 5], [1, 3, 5], [1, 4, 7]])
y = np.array([1,
              1,
              3])
print(x)
print(y)

[[1 2 5]
 [1 3 5]
 [1 4 7]]
[1 1 3]


In [73]:
x_transp = x.T
x_transp

array([[1, 1, 1],
       [2, 3, 4],
       [5, 5, 7]])

In [74]:
x_transp_mult = np.matmul(x_transp, x)
x_transp_mult

array([[ 3,  9, 17],
       [ 9, 29, 53],
       [17, 53, 99]])

In [75]:
x_transp_mult_inv = np.linalg.inv(x_transp_mult)
x_transp_mult_inv

array([[15.5,  2.5, -4. ],
       [ 2.5,  2. , -1.5],
       [-4. , -1.5,  1.5]])

In [76]:
left_part = np.matmul(x_transp, y)
left_part

array([ 5, 17, 31])

In [77]:
w = np.matmul(x_transp_mult_inv, left_part)
w

array([-4.00000000e+00, -7.10542736e-15,  1.00000000e+00])